name: Build Aseprite (Windows Only)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 触发
  push:
    branches: [ master, fix ]

env:
  BUILD_TYPE: Release

jobs:
  check-version:
    name: Check latest Aseprite release
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.version_info.outputs.latest_tag }}
      download_url: ${{ steps.version_info.outputs.download_url }}
      should_build: ${{ steps.should_build.outputs.should_build }}

    steps:
      - name: Get latest version info
        id: version_info
        run: |
          data=$(curl -sL https://api.github.com/repos/aseprite/aseprite/releases/latest)
          LATEST_TAG=$(echo "$data" | jq -r '.tag_name')
          DOWNLOAD_URL=$(echo "$data" | jq -r '.tarball_url')
          echo "latest_tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
          echo "download_url=$DOWNLOAD_URL" >> "$GITHUB_OUTPUT"

      - name: Check if version is cached
        id: version_cache
        uses: actions/cache@v3
        with:
          path: version.txt
          key: version-${{ steps.version_info.outputs.latest_tag }}

      - name: Should build?
        id: should_build
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" || "${{ steps.version_cache.outputs.cache-hit }}" != "true" ]]; then
            echo "should_build=true" >> "$GITHUB_OUTPUT"
            echo "${{ steps.version_info.outputs.latest_tag }}" > version.txt
          else
            echo "should_build=false" >> "$GITHUB_OUTPUT"
          fi

  build-aseprite:
    name: Build on Windows
    needs: check-version
    if: ${{ needs.check-version.outputs.should_build == 'true' }}
    runs-on: windows-latest

    steps:
      - name: Install build dependencies
        run: choco install ninja cmake -y

      - name: Download Skia (m124)
        run: |
          curl -L -o skia.zip https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip
          mkdir skia
          tar -xf skia.zip -C skia

      - name: Download Aseprite source
        run: |
          curl -L -o aseprite.tar.gz ${{ needs.check-version.outputs.download_url }}
          tar -xzf aseprite.tar.gz
          mv aseprite-* aseprite
          mkdir aseprite/build

      - name: Setup Visual Studio 2022
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.0'

      - name: Configure CMake
        working-directory: aseprite/build
        run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ^
            -DLAF_BACKEND=skia ^
            -DSKIA_DIR=../../skia ^
            -DSKIA_LIBRARY_DIR=../../skia/out/Release-x64 ^
            -DSKIA_LIBRARY=../../skia/out/Release-x64/skia.lib ..

      - name: Build with Ninja
        working-directory: aseprite/build
        run: ninja aseprite

      - name: Make portable
        working-directory: aseprite/build/bin
        run: echo "# Portable mode" > aseprite.ini

      - name: Create zip
        working-directory: aseprite/build/bin
        run: 7z a Aseprite-${{ needs.check-version.outputs.latest_tag }}-Windows.zip *

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite-${{ needs.check-version.outputs.latest_tag }}-Windows
          path: aseprite/build/bin/Aseprite-${{ needs.check-version.outputs.latest_tag }}-Windows.zip
